#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 13 12:35:51 EDT 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim AXI_top_tb_behav -key {Behavioral:sim_1:Functional:AXI_top_tb} -tclbatch AXI_top_tb.tcl -view /home/harigovind/Documents/dev/thesis/FPGA_BCP_acceleration/ip_repo/BCP_accelerator_2_0/hdl/AXI_top_tb_behav.wcfg -log simulate.log"
xsim AXI_top_tb_behav -key {Behavioral:sim_1:Functional:AXI_top_tb} -tclbatch AXI_top_tb.tcl -view /home/harigovind/Documents/dev/thesis/FPGA_BCP_acceleration/ip_repo/BCP_accelerator_2_0/hdl/AXI_top_tb_behav.wcfg -log simulate.log

