
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xclk_wiz.h"

/*
* The configuration table for devices
*/

XClk_Wiz_Config XClk_Wiz_ConfigTable[XPAR_XCLK_WIZ_NUM_INSTANCES] =
{
	{
		XPAR_CLK_WIZ_DEVICE_ID,
		XPAR_CLK_WIZ_BASEADDR,
		XPAR_CLK_WIZ_ENABLE_CLOCK_MONITOR,
		XPAR_CLK_WIZ_ENABLE_USER_CLOCK0,
		XPAR_CLK_WIZ_ENABLE_USER_CLOCK1,
		XPAR_CLK_WIZ_ENABLE_USER_CLOCK2,
		XPAR_CLK_WIZ_ENABLE_USER_CLOCK3,
		XPAR_CLK_WIZ_REF_CLK_FREQ,
		XPAR_CLK_WIZ_USER_CLK_FREQ0,
		XPAR_CLK_WIZ_USER_CLK_FREQ1,
		XPAR_CLK_WIZ_USER_CLK_FREQ2,
		XPAR_CLK_WIZ_USER_CLK_FREQ3,
		XPAR_CLK_WIZ_PRECISION,
		XPAR_CLK_WIZ_ENABLE_PLL0,
		XPAR_CLK_WIZ_ENABLE_PLL1,
		XPAR_CLK_WIZ_PRIM_IN_FREQ,
		XPAR_CLK_WIZ_NUM_OUT_CLKS
	}
};


